# Generated by Django 6.0.6 on 2026-08-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="prefix_name",
            field=models.CharField(
                choices=[("นาย", "นาย"), ("นาง", "นาง"), ("นางสาว", "นางสาว")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
